
spring:
  jackson:
    serialization:
      write-dates-as-timestamps: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost/postgres
    username: postgres
    password: infodba
  servlet:
    multipart:
      maxFileSize: 10MB # ?? ??? ?? ??
      maxRequestSize: 30MB  # ? ?? ?? ??? ?? ??
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: false

server:
  tomcat:
    max-http-form-post-size: 30MB
